# Generated by Django 3.1.5 on 2021-01-29 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210128_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
